# Generated by Django 3.0.11 on 2021-01-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('last_temperature', models.FloatField()),
                ('keep_alive', models.DateTimeField(auto_now_add=True)),
                ('threshold_temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.Device')),
            ],
        ),
    ]
