# Generated by Django 3.0.11 on 2021-01-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdevice',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
