# Generated by Django 3.0.11 on 2021-01-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alertdevice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
